export const STRAIN_DB = [
  { name:"Blue Dream",          type:"Hybrid", thc:21, cbd:2,  effects:["Relaxed","Happy","Creative"],   flavors:["Berry","Sweet","Earthy"],   description:"Balanced. Gentle cerebral lift." },
  { name:"OG Kush",             type:"Hybrid", thc:23, cbd:0,  effects:["Euphoric","Relaxed","Happy"],   flavors:["Earthy","Woody","Pine"],    description:"Classic. Deep euphoria and calm." },
  { name:"Sour Diesel",         type:"Sativa", thc:26, cbd:0,  effects:["Energetic","Happy","Uplifted"], flavors:["Diesel","Citrus","Earthy"], description:"Sharp energy. Fast cerebral hit." },
  { name:"Granddaddy Purple",   type:"Indica", thc:17, cbd:1,  effects:["Relaxed","Sleepy","Happy"],     flavors:["Grape","Berry","Sweet"],    description:"Deep relaxation. Sleep aid." },
  { name:"Wedding Cake",        type:"Hybrid", thc:25, cbd:0,  effects:["Relaxed","Euphoric","Happy"],   flavors:["Sweet","Vanilla","Earthy"], description:"Rich, creamy. Heavy euphoria." },
  { name:"Girl Scout Cookies",  type:"Hybrid", thc:28, cbd:0,  effects:["Euphoric","Happy","Relaxed"],   flavors:["Sweet","Earthy","Mint"],    description:"Powerful euphoria. Full-body." },
  { name:"Gorilla Glue #4",     type:"Hybrid", thc:27, cbd:0,  effects:["Relaxed","Euphoric","Sleepy"],  flavors:["Earthy","Pine","Woody"],    description:"Heavy relaxation. Couch-lock." },
  { name:"Jack Herer",          type:"Sativa", thc:18, cbd:0,  effects:["Energetic","Creative","Happy"], flavors:["Pine","Earthy","Spice"],    description:"Clear-headed. Creative spark." },
  { name:"Northern Lights",     type:"Indica", thc:18, cbd:0,  effects:["Relaxed","Sleepy","Happy"],     flavors:["Earthy","Sweet","Pine"],    description:"Classic indica. Night time." },
  { name:"Pineapple Express",   type:"Hybrid", thc:19, cbd:0,  effects:["Happy","Energetic","Creative"], flavors:["Tropical","Citrus","Pine"], description:"Tropical. Long-lasting energy." },
  { name:"White Widow",         type:"Hybrid", thc:20, cbd:0,  effects:["Happy","Euphoric","Creative"],  flavors:["Earthy","Woody","Floral"],  description:"Burst of euphoria and energy." },
  { name:"Green Crack",         type:"Sativa", thc:24, cbd:0,  effects:["Energetic","Focused","Happy"],  flavors:["Citrus","Earthy","Mango"],  description:"Sharp daytime focus." },
  { name:"Zkittlez",            type:"Indica", thc:23, cbd:0,  effects:["Relaxed","Happy","Euphoric"],   flavors:["Tropical","Berry","Citrus"],description:"Fruity. Calming body high." },
  { name:"Runtz",               type:"Hybrid", thc:29, cbd:0,  effects:["Euphoric","Happy","Relaxed"],   flavors:["Candy","Sweet","Tropical"], description:"Smooth. Potent euphoria." },
  { name:"Gelato",              type:"Hybrid", thc:26, cbd:0,  effects:["Happy","Relaxed","Euphoric"],   flavors:["Sweet","Earthy","Citrus"],  description:"Dessert flavour. Balanced." },
  { name:"Ice Cream Cake",      type:"Indica", thc:25, cbd:0,  effects:["Relaxed","Sleepy","Euphoric"],  flavors:["Vanilla","Sweet","Cake"],   description:"Sweet. Deep sedation." },
  { name:"Mimosa",              type:"Hybrid", thc:30, cbd:0,  effects:["Happy","Energetic","Uplifted"], flavors:["Citrus","Tropical","Sweet"],description:"Bright citrus. Uplifting." },
  { name:"Mac 1",               type:"Hybrid", thc:23, cbd:0,  effects:["Happy","Relaxed","Euphoric"],   flavors:["Floral","Earthy","Citrus"], description:"Creamy, balanced. Sought after." },
  { name:"Durban Poison",       type:"Sativa", thc:20, cbd:0,  effects:["Energetic","Happy","Creative"], flavors:["Sweet","Pine","Earthy"],    description:"African sativa. Uplifting." },
  { name:"Bubba Kush",          type:"Indica", thc:22, cbd:0,  effects:["Relaxed","Sleepy","Happy"],     flavors:["Earthy","Sweet","Woody"],   description:"Heavy tranquilising effects." },
  { name:"Purple Punch",        type:"Indica", thc:20, cbd:0,  effects:["Relaxed","Sleepy","Happy"],     flavors:["Grape","Berry","Sweet"],    description:"Sweet sedation. Night time." },
  { name:"Chemdawg",            type:"Hybrid", thc:19, cbd:0,  effects:["Relaxed","Euphoric","Happy"],   flavors:["Diesel","Chemical","Earthy"],description:"Cerebral. Heavy diesel." },
  { name:"Amnesia Haze",        type:"Sativa", thc:21, cbd:0,  effects:["Energetic","Happy","Uplifted"], flavors:["Citrus","Earthy","Sweet"],  description:"Uplifting citrus haze." },
  { name:"Do-Si-Dos",           type:"Indica", thc:28, cbd:0,  effects:["Relaxed","Sleepy","Euphoric"],  flavors:["Sweet","Earthy","Floral"],  description:"Potent. Fast-acting." },
  { name:"Bruce Banner",        type:"Hybrid", thc:29, cbd:0,  effects:["Euphoric","Happy","Creative"],  flavors:["Sweet","Earthy","Diesel"],  description:"Intense cerebral rush." },
  { name:"Harlequin",           type:"Sativa", thc:10, cbd:15, effects:["Relaxed","Focused","Happy"],    flavors:["Earthy","Sweet","Mango"],   description:"High CBD. Clear-headed." },
  { name:"ACDC",                type:"Hybrid", thc:6,  cbd:20, effects:["Relaxed","Calm","Focused"],     flavors:["Earthy","Pine","Woody"],    description:"Very high CBD. Minimal high." },
  { name:"Tangie",              type:"Sativa", thc:22, cbd:0,  effects:["Happy","Creative","Energetic"], flavors:["Citrus","Tropical","Sweet"],description:"Tangerine flavour. Creative." },
  { name:"Cherry Pie",          type:"Hybrid", thc:20, cbd:0,  effects:["Happy","Euphoric","Relaxed"],   flavors:["Cherry","Berry","Sweet"],   description:"Sweet cherry. Balanced." },
  { name:"Blueberry",           type:"Indica", thc:20, cbd:0,  effects:["Relaxed","Happy","Sleepy"],     flavors:["Berry","Sweet","Earthy"],   description:"Classic. Sweet blueberry." },
  { name:"Stardawg",            type:"Hybrid", thc:22, cbd:0,  effects:["Happy","Energetic","Uplifted"], flavors:["Diesel","Earthy","Pine"],   description:"Chemical-diesel. Uplifting." },
  { name:"Mochi",               type:"Hybrid", thc:29, cbd:0,  effects:["Relaxed","Happy","Euphoric"],   flavors:["Sweet","Earthy","Floral"],  description:"Creamy sweet. Potent." },
  { name:"Jealousy",            type:"Hybrid", thc:29, cbd:0,  effects:["Euphoric","Relaxed","Happy"],   flavors:["Sweet","Earthy","Candy"],   description:"Seed Junky classic." },
  { name:"Kosher Kush",         type:"Indica", thc:29, cbd:0,  effects:["Relaxed","Sleepy","Euphoric"],  flavors:["Earthy","Woody","Pine"],    description:"Exceptionally potent." },
  { name:"Permanent Marker",    type:"Hybrid", thc:30, cbd:0,  effects:["Euphoric","Relaxed","Creative"],flavors:["Fuel","Sweet","Earthy"],    description:"Pungent fuel. Heavy hitter." },
  { name:"Banana Runtz",        type:"Hybrid", thc:27, cbd:0,  effects:["Euphoric","Relaxed","Happy"],   flavors:["Tropical","Sweet","Candy"], description:"Banana candy. Potent." },
  { name:"Papaya",              type:"Indica", thc:25, cbd:0,  effects:["Relaxed","Happy","Sleepy"],     flavors:["Tropical","Mango","Sweet"], description:"Tropical. Deeply calming." },
  { name:"Crescendo",           type:"Hybrid", thc:32, cbd:0,  effects:["Euphoric","Relaxed","Creative"],flavors:["Diesel","Sweet","Earthy"],  description:"Extremely potent." },
  { name:"Sunset Sherbet",      type:"Hybrid", thc:21, cbd:0,  effects:["Happy","Relaxed","Creative"],   flavors:["Sweet","Berry","Citrus"],   description:"Fruity, balanced buzz." },
  { name:"Gary Payton",         type:"Hybrid", thc:25, cbd:0,  effects:["Euphoric","Focused","Happy"],     flavors:["Earthy","Pepper","Sweet"],  description:"Peppery, cerebral." },

  // ── Australian medical strains ──────────────────────────────────────────
  { name:"Topaz T25",           type:"Indica", thc:25, cbd:0,  effects:["Relaxed","Sleepy","Euphoric"],     flavors:["Earthy","Garlic","Diesel"],  description:"Kush Cookies. Heavy indica for sleep & pain." },
  { name:"ANTG Rocky",          type:"Indica", thc:30, cbd:0,  effects:["Relaxed","Sleepy","Euphoric"],     flavors:["Earthy","Pine","Woody"],     description:"El Jefe. Australian-grown medical heavyweight." },
  { name:"ANTG Solace",         type:"Sativa", thc:22, cbd:0,  effects:["Energetic","Happy","Focused"],     flavors:["Citrus","Earthy","Pine"],     description:"Tangie Chem. Daytime medical strain." },
  { name:"ANTG Mariposa",       type:"Sativa", thc:18, cbd:0,  effects:["Happy","Creative","Focused"],      flavors:["Sweet","Earthy","Citrus"],     description:"OG Kush. Gentle daytime flower." },
  { name:"Beacon GSC",          type:"Hybrid", thc:22, cbd:0,  effects:["Euphoric","Relaxed","Happy"],      flavors:["Sweet","Earthy","Mint"],       description:"Girl Scout Cookies. Popular clinic script." },
  { name:"Beacon Pink Kush",    type:"Indica", thc:25, cbd:0,  effects:["Relaxed","Sleepy","Euphoric"],     flavors:["Sweet","Earthy","Vanilla"],    description:"Barney's Farm. Canadian import." },
  { name:"Medcan CC01",         type:"Indica", thc:22, cbd:0,  effects:["Relaxed","Sleepy","Euphoric"],     flavors:["Earthy","Woody","Spice"],      description:"Cold Creek Kush. Afghan Kush x Chemdawg." },
  { name:"Cannatrek T20 Daylesford", type:"Indica", thc:20, cbd:0, effects:["Relaxed","Happy","Euphoric"],flavors:["Earthy","Sweet","Berry"],      description:"Death Bubba. Relaxing body stone." },
  { name:"Kind Stella",         type:"Indica", thc:18, cbd:1,  effects:["Relaxed","Calm","Focused"],        flavors:["Earthy","Sweet","Berry"],      description:"Death Bubba. Balanced medical strain." },
  { name:"SatiVite Lemon Haze", type:"Sativa", thc:22, cbd:0,  effects:["Energetic","Happy","Creative"],    flavors:["Lemon","Citrus","Sweet"],       description:"Super Lemon Haze. Uplifting daytime." },
  { name:"Tweed Bakerstreet",   type:"Indica", thc:20, cbd:0,  effects:["Relaxed","Sleepy","Happy"],        flavors:["Earthy","Sweet","Spice"],       description:"Hindu Kush. Classic sedating indica." },
  { name:"Spectrum Red No 1",   type:"Indica", thc:22, cbd:0,  effects:["Relaxed","Sleepy","Euphoric"],     flavors:["Earthy","Pine","Woody"],        description:"Pink Kush. Premium medical grade." },
  { name:"Althea THC25",        type:"Hybrid", thc:25, cbd:0,  effects:["Relaxed","Euphoric","Happy"],      flavors:["Earthy","Sweet","Citrus"],      description:"Rocky. Canadian import. Pain management." },
  { name:"Tilray THC25",        type:"Indica", thc:25, cbd:0,  effects:["Relaxed","Sleepy","Euphoric"],     flavors:["Earthy","Woody","Pine"],        description:"Master Kush. German medical import." },
  { name:"Adaya 26",            type:"Hybrid", thc:26, cbd:0,  effects:["Relaxed","Euphoric","Happy"],      flavors:["Earthy","Sweet","Diesel"],      description:"Gelato 33. High THC medical." },
];
